### ISSUE TITLE
[Question] Unit Testing for addons

### ISSUE THREAD

**Issue by hashhesh** [best-brands/analytics#1]
Hi @harm-smits
Thanks for your addon it helps a great deal.

I am just wondering if you tried to set up a unit testing for any plug in you are building or have built before. May I bother ask you to share the set up details/configurations?
It would be highly appreciated.

Please sorry for this question since it's out of this repo scope
Thanks in advance

**Comment by harm-smits** [comment]
These add-ons are usually a split from our monorepo, they get synced once in a while. By doing this we can utilize CsCart's testing code and run the same types of integration / unit tests. You can request access as a third party developer iirc.
